version: 2

sources:
  - name: data_tech_interview
    tables:
      - name: termination_reasons
        description: "termination reasons by transaction id"
      - name: transaction_details
        description: "transactions details table"
      - name: transactions_transitions_log
        description: "transactions log table to show change in stages"

      

